variavel = input('Digite algo: ')
print(f'O tipo primitivo é {type(variavel)}')
print(f'So tem espacos? {variavel.isspace()}')
print(f'É um número? {variavel.isnumeric()}')
print(f'É alfabético? {variavel.isalpha()}')
print(f'É alfanúmerico? {variavel.isalnum()}')
print(f'Está em maiúsculas? {variavel.isupper()}')
print(f'Está em minúsculas? {variavel.islower()}')
print(f'Está capitalizada? {variavel.istitle()}')

